/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE  from "three";

export default function Glitch({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/glitch.glb')
  useFrame(() => (group.current.rotation.x = group.current.rotation.y += 0.004)) 
  const material = new THREE.MeshStandardMaterial({
    color: 0x545454,
    transparent: true,
    opacity: 0.1,
    wireframe: true,
    roughness: 0
  })
  return (
    <group ref={group} {...props} dispose={null} position={[-2, 0, 0]}>
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_157.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_158.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_159.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_154.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_155.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_156.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_162.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_163.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_164.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_16.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_160.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_161.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_146.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_147.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_148.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_143.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_144.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_145.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_151.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_152.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_153.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_149.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_15.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_150.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_165.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_18.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_180.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_181.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_177.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_178.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_179.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_185.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_186.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_187.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_182.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_183.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_184.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_169.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_17.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_170.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_166.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_167.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_168.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_174.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_175.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_176.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_171.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_172.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_173.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_112.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_113.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_114.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_11.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_110.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_111.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_118.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_119.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_12.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_115.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_116.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_117.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_101.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_102.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_103.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_1.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_10.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_100.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_107.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_108.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_109.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_104.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_105.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_106.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_120.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_135.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_136.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_137.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_132.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_133.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_134.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_140.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_141.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_142.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_138.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_139.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_14.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_124.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_125.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_126.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_121.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_122.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_123.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_13.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_130.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_131.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_127.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_128.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_129.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_69.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_7.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_70.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_66.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_67.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_68.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_74.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_75.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_76.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_71.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_72.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_73.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_58.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_59.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_6.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_55.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_56.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_57.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_63.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_64.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_65.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_60.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_61.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_62.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_77.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_91.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_92.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_93.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_89.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_9.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_90.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_97.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_98.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_99.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_94.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_95.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_96.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_80.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_81.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_82.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_78.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_79.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_8.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_86.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_87.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_88.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_83.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_84.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_85.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_24.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_25.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_26.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_21.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_22.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_23.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_3.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_30.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_31.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_27.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_28.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_29.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_190.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_191.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_192.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_188.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_189.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_19.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_196.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_2.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_20.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_193.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_194.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_195.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_32.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_47.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_48.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_49.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_44.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_45.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_46.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_52.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_53.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_54.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_5.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_50.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_51.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_36.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_37.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_38.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_33.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_34.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_35.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_41.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_42.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_43.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_39.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_4.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale={0.035, 0.035, 0.035} geometry={nodes.object_40.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/glitch.glb')
