/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE  from "three";


export default function Matrix({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/matrix.glb')
  useFrame(() => (group.current.rotation.x = group.current.rotation.y += 0.006)) 
  const material = new THREE.MeshStandardMaterial({
    color: 0x545454,
    transparent: true,
    opacity: 0.1,
    wireframe: true,
    roughness: 0
  })
  const lenseMaterial = new THREE.MeshStandardMaterial({
    color: 0x545454,
    transparent: true,
    opacity: 0.1,
    roughness: 0
  })
  return (
    <group ref={group} {...props} dispose={null} position={[-2, 0, 0]}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh scale={0.02, 0.02, 0.02} geometry={nodes['matrix(2)_1'].geometry} material={material} />
        <mesh scale={0.02, 0.02, 0.02} geometry={nodes['matrix(2)_2'].geometry} material={material} />
        <mesh scale={0.02, 0.02, 0.02} geometry={nodes['matrix(2)_3'].geometry} material={lenseMaterial} />
      </group>
    </group>
  )
}

useGLTF.preload('/matrix.glb')
