/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE  from "three";

export default function Proxy({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/proxy.glb')
  useFrame(() => (group.current.rotation.y = group.current.rotation.z += 0.009)) 
  const material = new THREE.MeshStandardMaterial({
    color: 0x545454,
    transparent: true,
    opacity: 0.25,
    wireframe: true,
    roughness: 0
  })
  return (
    <group ref={group} {...props} dispose={null} position={[0, 0, 0]}>
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_1.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_2.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_3.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_4.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_5.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_6.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_7.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh scale ={0.04, 0.04, 0.04} geometry={nodes.object_8.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/proxy.glb')
